### ISSUE TITLE
Buscador de CUE no carga numero

### ISSUE THREAD

**Issue by renato2424** [fhatzen/geobra#101]
Si se utiliza el buscador de CUE, una vez encontrado el mismo, no lo pega en el campo de carga.
Esto obliga al operador a tipearlo si o si.

**Comment by fhatzen** [comment]
@elcrisa @tvalzacchi se mejoró el buscador, incorporando un botón "crear obra" dentro de la lista de establecimientos obtenida por el buscador, así se agiliza el proceso de carga del nro de CUE y ya no hará falta escribir en un papelito (gran avance!!)

![image](https://cloud.githubusercontent.com/assets/5720861/14148886/ec7a45d0-f677-11e5-8883-689dd1cf165d.png)

por favor René, es necesario que ASIGNES a fhatzen o a quien corresponda los casos creados en github, cualquier cosa pregunta a los expertos tomás o crisa
