### ISSUE TITLE
Agregar fecha de firma de contrato

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#102]
Fede, habría que agregar la fecha de firma de contrato

![image](https://cloud.githubusercontent.com/assets/17601411/14080407/4e610c78-f4db-11e5-956c-3b8103fd0cd4.png)

**Comment by fhatzen** [comment]
Agregada la fecha de contrato, por ahora en la solapa de fechas para mantener ese criterio. Igualmente insisto con mi idea de que los documentos adjuntados "manden": en este caso, en la solapa "contratista" se adjunta el contrato junto a su fecha, que podríamos asumir como "fecha de contrato". De lo contrario podríamos tener una inconsistencia si se carga una fecha en un lado y otra fecha en el otro lado. @elcrisa
