### ISSUE TITLE
Ordenar por numero de licitaciones

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#103]
No se ordena por licitaciones al seleccionar las flechitas

![image](https://cloud.githubusercontent.com/assets/17601411/14108288/04f3dfbc-f593-11e5-8e74-55135e102514.png)

**Comment by fhatzen** [comment]
Resuelto el orden por licitaciones (a partir de la actualización de hoy a la noche). Por favor recargar la aplicación completa presionando CTRL + F5 @elcrisa

**Comment by tvalzacchi** [comment]
Fede no estaría funcionando, recién lo probamos con Crisa y yo. Lo ideal sería que al seleccionar ver listado me las ordene por Programa y  N° de Licitacion, si fuera viable, y sino solo por N° de licitación

**Comment by fhatzen** [comment]
Tomi @elcrisa hice que el orden predeterminado sea nro. de licitación, pero de todas formas les pido que presionen CTRL + F5 en cada portátil para que se refleje esto, ya que está hecho y verificado que al cliquear sobre la flechita "licitación" ordena por tal columna, como lo muestro en la imagen aquí abajo (aunque recuerdo ayer que no parecía funcionar así en la portátil, por eso pido presionen CTRL + F5)

![image](https://cloud.githubusercontent.com/assets/5720861/14148033/48a27368-f674-11e5-8193-8ab88965a632.png)

**Comment by elcrisa** [comment]
no esta funcionando correctamente, fijate que no ordena correctamente los lotes dentro de cada cotizacion. Ademas para poder ordenar hay que tocar cualquier licitacion del listado y luego tocar el boton volver para recien ahi ordenarse.
![Uploading image.png…]()

**Comment by tvalzacchi** [comment]
Funciona si accedes desde Principal/Licitaciones/Buscar

Si accedes desde Ver listado no funciona aunque pongas Buscar

**Comment by fhatzen** [comment]
encontrado y corregido, ahora "ver listado" y "buscar" funcionan igual

**Comment by tvalzacchi** [comment]
Fede, ordena perfecto por licitación, lo único que faltaría sería que las ordene por lote dentro de cada licitación.

![image](https://cloud.githubusercontent.com/assets/17601411/14152219/66690d6c-f688-11e5-975f-6a96e770f844.png)
