### ISSUE TITLE
Datos por default en FREC

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#104]
Estas cosas acelerarían el data entry..  En FREC

Tipo de contratación: **CE**
Medicion y certificación: **Quincenal**

**Comment by fhatzen** [comment]
Agregada la posibilidad de especificar, por "programa", el tipo de contratación y periodicidad de la medición. Además de especificar los documentos que deben formar parte de las licitaciones en ese programa. Para facilitar esto último se agregó un botón para copiar documentos de un programa a otro. Esto estará disponible a partir de la actualización de hoy a última hora
