### ISSUE TITLE
Flechas rojas no necesarias

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#107]
Deberíamos eliminar las flechitas rojas de orden en CUE y en Establecimiento ya que no se van a utilizar

![image](https://cloud.githubusercontent.com/assets/17601411/14147763/332b80ac-f673-11e5-8eba-78c29600b7c2.png)

**Comment by fhatzen** [comment]
@elcrisa eliminadas las flechas rojas
