### ISSUE TITLE
Especificar que lotes fueron cargados

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#108]
Ver que lotes tienen cargados en solapa Propuestas

![image](https://cloud.githubusercontent.com/assets/17601411/14180825/117a0992-f73b-11e5-8c0b-b8473c9e47cd.png)

**Comment by fhatzen** [comment]
Se muestran todas las ofertas del expediente, en cualquiera de los lotes del mismo, pudiendose editar sólo la oferta del lote actual.

@elcrisa Dejo de actualizar G-OBRA en este punto, por favor verificar mañana el funcionamiento ya que metí mucha mano, de forma de poder corregir bugs a la noche en cuanto tenga disponibilidad

![image](https://cloud.githubusercontent.com/assets/5720861/14223827/eedfe59a-f85d-11e5-9f72-5fe225b0d4c6.png)
