### ISSUE TITLE
Tema ordenar por Estado

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#110]
Fede, pasa algo raro al ordenar por Estado, solo pone en Contratada 3 lotes de distintas licitaciones, y no pone el resto de los lotes de esa licitación, y hay licitaciones con contratistas seleccionados que no aparecen en contratada.

![image](https://cloud.githubusercontent.com/assets/17601411/14207329/c1713e74-f7ef-11e5-8009-039b2cd4b334.png)

También te comento lo que hablamos ayer con Luciano, y es que apuntamos a la reunión del Lunes un mapa con colores de globitos por estados. Por ahora hablamos con @elcrisa que se vean 3 Estados, por ende nos faltaría agregar el estado Llamada, es cuando se cargan las empresas invitadas, y no hay Contratista designado Previo a esto cualquier licitacion será Elegibilidad. Apuntamos al lunes a tener estos 3 estados nada más para poder generar el impacto visual del mapa por Estados.

Datos para que necesitaría @lfantone para el mapa:

En elegibilidad: Establecimiento - Programa - N°Lic y Lote - Presup. Oficial

Llamada: Establecimiento - Programa - N°Lic y Lote - Presup. Oficial

Contratada: Establecimiento - Programa - N°Lic y Lote - Monto contratado

**Comment by fhatzen** [comment]
@tvalzacchi @elcrisa @marcos-zampetti @lfantone vamos por partes aquí.
1) la parte del mapa la pasé a un github separado
2) los estados NO se estaban cambiando ya que no había una indicación precisa, sólo le asigné un estado general a todos los contratos en su momento
3) en virtud de este pedido, asigné estados a las licitacion según tu indicación
4) también incorporé dos formas de cambio de estado: 
- la NATURAL se produce como consecuencia de adjuntar documentos (si se adjunta un "contrato", por ejemplo, la licitación pasará al estado "ADJUDICADA" ya que ese es el estado al que pertenece tal contrato; esto significa también que desde configuración - documentos se puede manipular el funcionamiento de esto; agrego también que por ahora los estados sólo SUBEN, si se adjunta un documento correspondiente a estados anteriores, la licitación permanece en su estado actual)
- la ARBITRARIA: desde carátula es posible cambiar la licitación a cualquier estado que se desee
