### ISSUE TITLE
Cartel inconsistente

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#113]
Fede, al ir a mediciones salta este cartel

![image](https://cloud.githubusercontent.com/assets/17601411/14213200/0f94b942-f80d-11e5-9fd5-62e11b64882b.png)

**Comment by fhatzen** [comment]
Corregido. Había inconsistencia, pero en el tercer decimal, fijaos. @elcrisa 

![image](https://cloud.githubusercontent.com/assets/5720861/14218675/1c472cd2-f82c-11e5-84fa-da03a91a1eed.png)
