### ISSUE TITLE
sin distrito

### ISSUE THREAD

**Issue by marcos-zampetti** [fhatzen/geobra#114]
Fede la licitación 29/16/6 estaba mal cargada en el número de CUE, la modifique y ahora me tira que no tiene distrito, región ni establecimiento.

![imagen](https://cloud.githubusercontent.com/assets/18214286/14214213/217c4e5e-f812-11e5-8cac-7f0b15e80d28.jpg)

**Comment by fhatzen** [comment]
Resuelto. Por favor recargar el programa (CTRL + F5) y modificar nuevamente el número de CUE para verificar que ya funciona correctamente (primero colocar cualquier otro, verificar, luego colocar el correcto y verificar)
