### ISSUE TITLE
Errores en UM Mediciones

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#115]
En mediciones no toma la Unidad de Medida del C y P contratado, sino que trae las UM del C y P oficial

![image](https://cloud.githubusercontent.com/assets/17601411/14214290/aaa4218e-f812-11e5-8f84-90eaba5de2fd.png)

![image](https://cloud.githubusercontent.com/assets/17601411/14214340/f49e7a64-f812-11e5-951b-9afe662e4a8e.png)

Una vez guardado, o digamos generado el C y P, no se debería poder modificar. Por ejemplo, si alguien lo modifica, y ya tengo el certificado 1 generado, cuando haga el 2 no van a coincidir. No se si me explique bien

**Comment by fhatzen** [comment]
Corregido el error. También se incorporó que NO se pueda modificar CyP contratado una vez que existe al menos 1 certificado con PDF generado.
