### ISSUE TITLE
Pantalla login (no quema)

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#117]
Al ingresar es, completa usuario, clave, y uno presiona ENTER en clave, y no funciona. Estaría bueno, cuando se pueda, que al hacer enter directamente ingrese a g-obra como estaba antes

**Comment by fhatzen** [comment]
Resuelto. Asimismo, en pantalla de lista de licitaciones, el ENTER funciona como clickear en "buscar"
