### ISSUE TITLE
No se estan mostrando las fotos ni en caratula ni en memoria tecnica 

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#119]
![image](https://cloud.githubusercontent.com/assets/17600443/14223945/be02b41c-f861-11e5-9271-02be45d705b4.png)
![image](https://cloud.githubusercontent.com/assets/17600443/14223949/c369af1e-f861-11e5-97e5-4f9111d798ee.png)

**Comment by elcrisa** [comment]
al menos en esta licitacion

**Comment by fhatzen** [comment]
Resuelto este lío
