### ISSUE TITLE
Licitación oferta lote 6

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#123]
Fede, no deja cargar en oferentes el lote 6, sucede en la licitación 29. No se sabemos pq, es en la única q se esta cargando una oferta en un sexto lote, sospechamos que será por eso y que solo deja 5

![image](https://cloud.githubusercontent.com/assets/17601411/14251353/ee293b4a-fa58-11e5-91b9-0eab5af103dc.png)

**Comment by fhatzen** [comment]
Corregido y explicado en otro github
