### ISSUE TITLE
No se pueden cargar ofertas de los distintos lotes

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#125]
Fede, no se si modificaste algo, pero no se pueden cargar montos de oferta por los distintos lotes. El caso del ejemplo es la 68 que solo deja ver oferta de lote y no muestra el resto

![image](https://cloud.githubusercontent.com/assets/17601411/14259203/41f1b7b6-fa7c-11e5-9bb7-d14855dcf106.png)

**Comment by fhatzen** [comment]
corregido este bug (se avisó durante la tarde a @elcrisa )
