### ISSUE TITLE
licitacion 31/16/3 no se vizualiza el avance certificado carrgado en mediciones

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#131]
si bien se cargaron mediciones no se muestran.
![image](https://cloud.githubusercontent.com/assets/17600443/14289736/7a8f36c8-fb32-11e5-850f-0dfb3ad5fec4.png)
![image](https://cloud.githubusercontent.com/assets/17600443/14289756/961deb46-fb32-11e5-8203-de54b34fec2a.png)

**Comment by fhatzen** [comment]
no encontré la razón de este error, los avances se van guardando (y reflejando tanto en lista de licitaciones como en solapa montos de la licitación) a medida que se ingresa el % de avance de CADA ITEM; por favor verificarlo con alguna otra licitación realizando la carga uds. mismos
