### ISSUE TITLE
No se pueden generar PDF´s de los certificados

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#132]
![image](https://cloud.githubusercontent.com/assets/17600443/14289794/ba0416d4-fb32-11e5-816f-48ed4d6bfbe3.png)
![image](https://cloud.githubusercontent.com/assets/17600443/14289800/c0f490d6-fb32-11e5-8739-44f9a3d1146d.png)

**Comment by fhatzen** [comment]
Corregido. Ojo que pronto no se podrá generar PDF de certificado si no están las fotos de la medición (hay un alerta por ahora) @tvalzacchi
