### ISSUE TITLE
No se puede eliminar licitacion 300/2016/1 

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#134]
no funcionan los botones de eliminar y confirmar eliminación al menos en esta licit. (300/2016/1 )
![image](https://cloud.githubusercontent.com/assets/17600443/14318130/d38373fc-fbe1-11e5-9622-12c3a38012a2.png)

**Comment by tvalzacchi** [comment]
Recien probe y la pude eliminar
