### ISSUE TITLE
Grupo de lotes

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#17]
En primer página poder ver agrupados los Lotes (agrupados por expediente)

**Comment by tvalzacchi** [comment]
@elcrisa como seguimos con esto?

**Comment by tvalzacchi** [comment]
O para resolver ahora se podría filtrar por número de licitación

**Comment by fhatzen** [comment]
estimados, cambié la vista predeterminada a un agrupamiento por expedientes, de forma que los distintos lotes aparezcan juntos; recordar que clickeando en las flechitas rojas se agrupa por el campo clickeado
