### ISSUE TITLE
Eliminar rubros sin contenido

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#20]
Eliminar u ocultar los rubros sin contenido.
![image](https://cloud.githubusercontent.com/assets/17600443/13480051/f1355e4e-e0b9-11e5-8e8f-1e0e985c54ba.png)

**Comment by elcrisa** [comment]
Una vez que se presiona Guardar o se sale de esta pantalla ( si estoy trabajando en ella se muestra tal cual la imagen subida anteriormente), al volver solo se deberia mostrar los rubros con contenido (y por ende sus items). Si quisiera seguir trabajando deberia presionar un boton "editar" y ahi si veo la pantalla con rubros que no contengan ningun item ya que me encuentro en modo edicion. Deberia ser similar a la del presupuesto contratado si no estoy editando, como esta ahora esta todo el tiempo en modo edicion.

**Comment by fhatzen** [comment]
así fue hecho, según la indicación, con botón "+ rubros" para desplegar los rubros no marcados
