### ISSUE TITLE
"monto contrato original" deberia  ser la suma del "computo y presupuesto contratado" o sea mismo valor que "monto suma items"

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#21]
![image](https://cloud.githubusercontent.com/assets/17600443/13480203/fafcd51e-e0ba-11e5-8264-1817ee596d3a.png)

**Comment by fhatzen** [comment]
el campo monto contrato original (que se carga manualmente) lo usamos como validación contra "suma monto itemos contratado" (que no sabemos si se cargará manualmente, por importación, por carga directa del contratista al cotizar etc. etc.), los dejamos para ser cargados separadamente como forma de validación
