### ISSUE TITLE
Cuadro comparativo ofertas

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#24]
Agregar solapa Cuadro comparativo de ofertas (creo que desp. de Montos o de CyP oficial) para las frec no pueden haber más de 6 ofertas, ordenadas por menor monto cotizado, agregar tilde de cumplimiento o no de requisitos exigidos

**Comment by tvalzacchi** [comment]
Por favor, tener en cuenta este requerimiento

![image](https://cloud.githubusercontent.com/assets/17601411/13613262/228f68e2-e54a-11e5-9890-f95ee911bb28.png)

**Comment by tvalzacchi** [comment]
esto vendría a ser la misma solapa que en el issue #40 mencionaba como oferentes

**Comment by fhatzen** [comment]
Agregada la solapa "oferentes" con el cuadro comparativo de ofertas, las cuales se ingresan por CUIT que se conecta con la base de AFIP; en la solapa siguiente "contratista" sólo se verán contratistas que se hayan cargado en solapa "oferentes"

**Comment by tvalzacchi** [comment]
El orden de presentación debe ser automático ordenado de menor a mayor monto de oferta

**Comment by tvalzacchi** [comment]
Esta solapa, tendría que tener la posibilidad de adjuntar el **Acta de apertura de ofertas**

La misma tendría que estar antes del cuadro comparativo (Puede estar arriba)

Este sería uno de los hitos que estan en la etapabilidad que estamos manejando

**Comment by tvalzacchi** [comment]
En referencia a esta acta, debería poder agregarse un campo para completar la Fecha del acta de apertura de ofertas. Luego otro para completar con el Período de validez de Oferta, en los casos que vi son de 90 dias, pero por las dudas debería ser editable. Y uno que con estos datos me determine la fecha de vencimiento de la oferta

**Comment by elcrisa** [comment]
![image](https://cloud.githubusercontent.com/assets/17600443/13644195/48696680-e603-11e5-8059-e6cd33a4160a.png)
Solo debe poder adjuntar el acta de Apertura de ofertas (no ver ninguna lista de opciones, ni estados, confunde)

**Comment by fhatzen** [comment]
realizada la indicación de crisafulli, se ocultan las opciones innecesarias

**Comment by elcrisa** [comment]
![image](https://cloud.githubusercontent.com/assets/17600443/13647692/01766afa-e614-11e5-885f-e61f7c703ab9.png)
Eliminar Fecha junto a cada oferente, ordenar por monto ofertado (el menor valor primero).
En la solapa contratista, elegir en el desplegable que debera tener los cargados en oferentes en ese orden.

-

**Comment by tvalzacchi** [comment]
Fede nos surgio un tema, es que el acta y los oferentes van por todos los lotes. Tenemos que reunirnos y hablarlo para ver que posibilidad hay de unificar la solapa oferentes para un mismo lote, o si toma de referencia al resto. Todos los lotes siempre se asignan a un mismo oferente. Adjunto un cuadro comparativo con varios lotes:

![image](https://cloud.githubusercontent.com/assets/17601411/13648040/9eb6d1c8-e615-11e5-8e42-b8477b26d52d.png)

**Comment by fhatzen** [comment]
eliminada la fecha junto a cada oferente, el orden es por monto ofertado y la solapa contratista muestra una lista de los oferentes, agregando ahora el monto ofertado y ordenando por este campo

**Comment by tvalzacchi** [comment]
reabro por el comentario que hice justo antes de q la cierres, ahi t llama crisa

**Comment by fhatzen** [comment]
Se modificó esta pantalla para que muestre los montos acumulados por contratista de todas las ofertas de distintos lotes dentro del mismo expediente

Además se agregó la posibilidad de adjuntar los documentos requeridos (que no sé cuales son), esto reemplazaría "tilde de cumplimiento o no de requisitos exigidos"

**Comment by tvalzacchi** [comment]
Cargue una de prueba, la licitación 2, cargue el lote 1, y al ir al lote 2 me debería llevar los mismos oferentes

![image](https://cloud.githubusercontent.com/assets/17601411/13668158/a6b89e68-e699-11e5-9f0a-bb14ed590edd.png)


![image](https://cloud.githubusercontent.com/assets/17601411/13668169/bc6f904a-e699-11e5-8844-beb3aa2298be.png)

**Comment by tvalzacchi** [comment]
Por favor fede recorda lo del período de validez de ofertas que mencione antes

**Comment by tvalzacchi** [comment]
Fede, el acta de apertura es por todos los oferentes, no habría que seleccionar 1

![image](https://cloud.githubusercontent.com/assets/17601411/13668319/cd14ec8c-e69a-11e5-88ae-24c0fc3d5c60.png)

**Comment by fhatzen** [comment]
doy por resuelto este github, los datos de oferentes pasaron a una nueva entidad "expediente",que puede contener varias licitacions; un conratista creado como oferente en cualquiera de las licitaciones aparece en todas aquellas que forman parte del grupo, esperando que se les complete el monto ofertado
