### ISSUE TITLE
usuario VE TODO

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#26]
NO debe poder cambiar distrito en establecimientos, no debe poder hacer observaciones

**Comment by fhatzen** [comment]
Resuelto este github. Los usuarios ya se establecen como "ve todo / modifica / elimina" a nivel de menú principal / configuración / el que venga, por favor miralo en configuración - usuarios, agrego imagen

![image](https://cloud.githubusercontent.com/assets/5720861/13613562/6cba84a0-e54b-11e5-97e1-ce0a63a86e25.png)
