### ISSUE TITLE
Carga de fotos

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#27]
Tardan mucho en cargarse las miniaturas, las ubica de modo extraño (cargue 8)
![image](https://cloud.githubusercontent.com/assets/17600443/13528901/d75bfc82-e1f7-11e5-9db7-27af5fa9e585.png)

**Comment by elcrisa** [comment]
Colocar junto a elegibilidad : (Relevamiento)
Entre parentesis y es posible al cargar la foto permitir colocar fecha y una descripcion a modo de "pie de foto"

**Comment by elcrisa** [comment]
Estaria muy bueno cargar solo 4 fotos que esten el mismo tamaño y de haber mas fotos colocar un boton "+ FOTOS" y recien ahi cargarlas. el tema es que si son muchas fotos como en el caso de la 1/2016/1 se hace muy "larga" la pantalla y lenta la carga de miniaturas.

**Comment by fhatzen** [comment]
Se acomodaron las fotos. Se introdujo la creación de una miniatura real, de bajo peso en KB, para lo cual se ELIMINARON los adjuntos anteriores (por favor subir nuevamente). Con esto se resuelve la cantidad de fotos mostradas. Se modificó la leyenda en el estado Elegibilidad ("relevamiento").

**Comment by elcrisa** [comment]
Esto fue resuelto parcialmente:"Estaria muy bueno cargar solo 4 fotos que esten el mismo tamaño y de haber mas fotos colocar un boton "+ FOTOS" y recien ahi cargarlas. el tema es que si son muchas fotos como en el caso de la 1/2016/1 se hace muy "larga" la pantalla y lenta la carga de miniaturas."

**Comment by fhatzen** [comment]
Crisa, tené en cuenta que las miniaturas son ahora realmente miniaturas (menos de 6 / 7 kb cada una), por esa razón las dejé todas.... capaz le podemos dejar al programador la tarea de que sea una barra scrolleable o algo así, pero me pareció que las podemos dejar ya que están al fondo y no molestan.

Además me encontré con el problema de que las fotos pertenecen a estados, si mostramos sólo cuatro las mismas pertenecerán a un estado aleatorio (o el más actual), quedando sin posibilidad de observarse el "antes" y "después" de la obra

Si estás de acuerdo generalo como un github diferente, asignado al milestone "a desarrollar por programador", si no reabrime este para una resolución para zafar.

**Comment by elcrisa** [comment]
Creo que no se lo podemos dejar a Horacio ya que no es un reporte sino una vista rapida de fotos. La propuesta amen que se trate de miniaturas es que no quede una pagina laaarrrrrggggaaaaaa nada mas. Es imposible colocar 4 fotos y el boton mas fotos asi : F   F   F   F   +fotos...
al clickear mostrame la s fotos tal cual se ven ahora (todas)

**Comment by fhatzen** [comment]
resuelto tu caprichito crisa
