### ISSUE TITLE
pantalla Inicio botón Solo subtotales

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#28]
Fede solo subtotales debería ser posible solo despues de que haya seleccionado Ver montos

![image](https://cloud.githubusercontent.com/assets/17601411/13529859/1487165a-e1fd-11e5-9389-a8af234ab480.png)

**Comment by fhatzen** [comment]
resuelto, al clickear "solo subtotales" se clickea automáticamente "ver montos" sino estuviera clickeado
