### ISSUE TITLE
Usuario infraestructura

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#30]
No ver Configuración, Establecimientos pasa a Principal

**Comment by tvalzacchi** [comment]
No ver botón eliminar

**Comment by tvalzacchi** [comment]
En USUARIOS poder asignar el tipo de usuario

**Comment by tvalzacchi** [comment]
Usuario Infraestructura no puede cambiar solapas

**Comment by fhatzen** [comment]
resuelto, con comentarios en la imagen

![image](https://cloud.githubusercontent.com/assets/5720861/13581415/862940c8-e485-11e5-949b-9d0511b5f710.png)
