### ISSUE TITLE
pantalla despues del login (inicio)

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#33]
cargo la propuesta de pantalla despues del login
![uep-pantalla inicial-01](https://cloud.githubusercontent.com/assets/17601411/13603926/38bb4d78-e51f-11e5-8a0f-fae0a3ca0c43.jpg)

**Comment by elcrisa** [comment]
en el sector de "descargas, instructivos, plugins" agregar las "fuentes" al clickear se muestra txt: (ej: Origen datos CUE, origen Mapa Regiones, Origen Datos Establecimientos, etc)

**Comment by tvalzacchi** [comment]
@renesou Con quien seguimos este tema?

**Comment by tvalzacchi** [comment]
Fede, habría que traer también asi como está, el ''datos personales'' del sistemo al cuadrito de la derecha

![image](https://cloud.githubusercontent.com/assets/17601411/13703504/61ffda02-e775-11e5-9bef-e7d85d418dcd.png)

**Comment by tvalzacchi** [comment]
-El nombre se debe ver pero no poder cambiar.

-En clave nueva, habría que poner el mismo link que solicitó @elcrisa en el #63

**Comment by fhatzen** [comment]
Doy por cerrado este github general para que vayamos luego creando los pedidos particulares de cada sección

**Comment by fhatzen** [comment]
ya está subida una nueva home según la indicación

**Comment by tvalzacchi** [comment]
Adjunto las modificaciones vistas hoy

![uep-pantalla inicial-02](https://cloud.githubusercontent.com/assets/17601411/13831613/d9046dba-ebb3-11e5-9ea0-38b87a343086.jpg)

**Comment by fhatzen** [comment]
estas modificaciones fueron realizadas y subidas

**Comment by tvalzacchi** [comment]
Fede reabro este tema para proponer una solución provisoria, hasta que este lo del maps. También te consulto porque no se puede elegir **Cambiar clave**

![uep-pantalla inicial-03](https://cloud.githubusercontent.com/assets/17601411/13884275/0f78c964-ed0c-11e5-8689-f3de0b00f2f7.jpg)

**Comment by tvalzacchi** [comment]
Fede, lo del cambiar clave quema quema
