### ISSUE TITLE
Reordenamiento solapas

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#40]
-Llevar campo y datos de Inspector de la solapa **Datos generales** a **Caratula**

-Solapa **Datos generales** debería llamarse **Contratista**

-Agregar solapa **Oferentes**

-Por orden cronológico, quedaría ahora:

CARATULA - FECHAS - MONTOS - C Y P OFICIAL - OFERENTES - CONTRATISTA - C Y P CONTRATADO - ETC..

**Comment by fhatzen** [comment]
reordenadas las solapas segun indicado
