### ISSUE TITLE
Agregar unidad en items, tomar el mismo contenido desplegable de sistemo (ml, m2, m3, ...,bolsa, etc...)

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#41]

**Comment by fhatzen** [comment]
Agregada la posibilidad de establecer unidad

**Comment by tvalzacchi** [comment]
@fhatzen fijate que hay 2 de m2 y 2 de m3, nosotros no podemos mod ni agregar unidades de medida

**Comment by tvalzacchi** [comment]
hay 2 ML

**Comment by fhatzen** [comment]
ya pueden modificar y eliminar unidades desde el menú configuración (verificar que tienen, como usuarios, el permiso de eliminación en menú configuración)
