### ISSUE TITLE
Ocultar curva de inversion FREC

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#42]
En plan de obras FREC que no se vea la solapa **Curva de inversión**

**Comment by fhatzen** [comment]
a discutir: qué parámetros dependen de "programa"? tenemos que pensarlo más amplio para luego impleentarlo

**Comment by tvalzacchi** [comment]
Con respecto a este tema en el pliego de particulares FREC si se solicita, deberíamos dejarla y ver cuando avancemos con la carga de las obras si disponen de esta información o no, por ende doy para atrás con el pedido inicial.
