### ISSUE TITLE
Ideas sobre fotos, relevamiento y certificados

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#44]
Estamos pensando en una posible solapa llamada **Relevamiento** la cual debería tener un campo para completar con la _fecha de relevamiento_, y otro para completar con una _memoria descriptiva_ de buen tamaño. 

@fhatzen hay posibilidades de que los adjuntos se suban solo donde corresponden? es decir, en la pantalla donde certifico adjunto fotografias relacionadas a ese certificado.

Esta bueno como está ahora que en la **Carátula** se vean las ultimas fotos, es decir que si ya hay fotos del Cert 1 me tome las mismas

**Comment by fhatzen** [comment]
Estimados, los adjuntos se subirán sólo donde corresponde, hoy por hoy tenemos una sola sección donde subir adjuntos en la cual es necesario indicar estado, certificado, etc.; en cuanto implementemos un workflow será al revés, el sistema ya sabrá estado, certificado, etc y obligará a subir fotos o documentos (hitos) según establezcamos para dicho estado / estado de certificado

Agregué la solapa "relevamiento" (por favor distintos temas pedirlos en distitos githubs)

**Comment by tvalzacchi** [comment]
Yo no le veo utilidad a un relevamiento sin fotos

**Comment by fhatzen** [comment]
lo que hice fue mostrar, en la solapa "relevamiento" las imágenes correspondientes al estado "relevamiento" (si es que se subió alguna, manualmente, con el botón adjuntos)

en el futuro el estado "en elegibilidad - relevamiento" será parte de workflow, contando con su propio botón de adjuntar imágenes y documentos
