### ISSUE TITLE
No se ven licitaciones

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#45]
Estimado, creo este github para que no se mezcle con otros

![image](https://cloud.githubusercontent.com/assets/17601411/13612509/a00f3e7c-e546-11e5-999d-2e0ddd4f26a8.png)

**Comment by fhatzen** [comment]
por favor dale CTRL + F5 para actualizar la versión, de lo contrario cerrar y abrir sesión nuevamente, de lo contrario decime si estabas haciendo una búsqueda particular

**Comment by elcrisa** [comment]
Yo no veo tampoco, da error
![image](https://cloud.githubusercontent.com/assets/17600443/13612919/a02642a0-e548-11e5-8fcc-aced6ccdfe93.png)

**Comment by elcrisa** [comment]
Corregido
