### ISSUE TITLE
Representante técnico

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#46]
El representante técnico actual de la solapa contratista debe ser un campo editable. El desplegable que tiene ahora, sería el Supervisor, debería ir arriba del inspector en pantalla carátula

**Comment by elcrisa** [comment]
![image](https://cloud.githubusercontent.com/assets/17600443/13636491/fd63a67c-e5e0-11e5-8feb-0059a7d35467.png)
Al elegir de la lista desplegable de representante tecnico, los datos que aparecen son nombres de Supervisores. Para el dato de representante tecnico poner un campo editable (no una lista).
![image](https://cloud.githubusercontent.com/assets/17600443/13636575/57e044e8-e5e1-11e5-88bb-5624d8259d05.png)
Sobre el campo inspector irian los "Supervisores" y ahi si va el desplegable con los datos antes mencionados.

**Comment by fhatzen** [comment]
la carga de representante técnico quedó como se la pide
los supervisores son ahora coordinadores regionales y no se cargan sino que vienen automáticamente de la región de la escuela
