### ISSUE TITLE
Busqueda de establecimientos

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#47]
En la busqueda por establecimientos, debería buscar solamente los campos establecimientos, ahora pareciera que busca en otros campos tambien, adjunto imagen de referencia

![image](https://cloud.githubusercontent.com/assets/17601411/13621122/d8981f02-e573-11e5-8938-6d72a1c307e1.png)

**Comment by fhatzen** [comment]
Restringido el ámbito de búsqueda al texto del nombre de la escuela
