### ISSUE TITLE
Inconsistencias a resolver en Establecimientos

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#49]
Fede surgió un tema acá referente a los CUE y los establecimientos con este caso:

El CUE que cargamos es el correcto (referente al mapa educativo), pero creemos que en el excel ese CUE esta mal vinculado al campo establecimiento (por eso trae la 68 a g-obra)

![image](https://cloud.githubusercontent.com/assets/17601411/13641791/8fc9241c-e5f8-11e5-9617-0d8aba47547f.png)
![image](https://cloud.githubusercontent.com/assets/17601411/13641799/99c89a6a-e5f8-11e5-8b03-ba1f3f0b6c71.png)

En la información recibida es la ES N39. Fuimos con Street View y confirmamos esto y si, es la N°39, por ende es una inconsistencia en el excel. El tema es ver si es una excepción y también como lo podemos resolver.

![image](https://cloud.githubusercontent.com/assets/17601411/13641874/fa2b94a2-e5f8-11e5-92f8-ffb7f708cf32.png)

**Comment by elcrisa** [comment]
Aca dos bases Mae de 2014 y (la que usamos de 2016), entiendo que cambio de nombre entre 2014 y 2016.
![image](https://cloud.githubusercontent.com/assets/17600443/13642417/2733968c-e5fb-11e5-9809-951fc80d178f.png)

**Comment by tvalzacchi** [comment]
Viendo bien, el relevamiento era de hace unos años, yo explico por ahi esta diferencia, la cierro asi no se acumulan viejas issues abiertas
