### ISSUE TITLE
Tema modalidad

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#50]
Con respecto a la modalidad, como deciamos en otro mail, la misma no debería ser un campo editable, sino que se debería poder extraer del mismo listado de establecimientos. También genera quilombo ya que en los documentos de la UEP la modalidad de las obras se refiere al modo de contratación, es decir por Ajuste alzado. Por ende ese filtro deberíamos sacarlo del listado de licitaciones

![image](https://cloud.githubusercontent.com/assets/17601411/13644462/acbc3800-e604-11e5-9b16-6b6313d6d124.png)

![image](https://cloud.githubusercontent.com/assets/17601411/13644539/113a0dde-e605-11e5-895e-3eecbd611e1c.png)

**Comment by fhatzen** [comment]
eliminada la modalidad, en el nombre del establecimiento está bastante descriptivo y si hace falta lo incorporamos nuevamente
