### ISSUE TITLE
datos de la solapa "contratista"

### ISSUE THREAD

**Issue by fhatzen** [fhatzen/geobra#51]
el dato "modalidad" ya desapareció al igual que "superficie nueva" y "superficie refacción" (que los interpreté erróneamente por algo leído en el pliego), queda sólo para reubicar el dato "tipo de obra",  que para mí debería ir algún lugar de la obra, capaz la solapa, confirmame pla

![image](https://cloud.githubusercontent.com/assets/5720861/13646293/83ec276a-e60d-11e5-8b08-a718ba08e4f3.png)

**Comment by tvalzacchi** [comment]
Tipo de obra debería estar en Carátula

**Comment by tvalzacchi** [comment]
Fede, en esta misma solapa, si te parece, podríamos incluir los hitos necesarios para el cambio hacia el próximo cambio de estado. Estos están vinculados al contratista:

1- El nombre podría ser **Planos de proyecto y documentación técnica aprobados** y que solo pueda adjuntar un .rar

2-El nombre podría ser **Seguros** en total pide 8 seguros

3-Podría también estar El Acta de inicio, pero de esto no estoy seguro, lo estamos viendo donde ponerla.

**Comment by fhatzen** [comment]
Realizados estos ajustes en la solapa "contratista"
