### ISSUE TITLE
Texto solapa relevamiento

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#52]
Fede, el campo para escribir el **relevamiento** debe ser amplio (por lo menos 5000 caracteres) y con la posibilidad de poner puntos y aparte, subrayados, etc.

**Comment by tvalzacchi** [comment]
Ahora entran muy pocos

![image](https://cloud.githubusercontent.com/assets/17601411/13722855/affe2f4e-e831-11e5-8e2a-028d31e69145.png)

**Comment by tvalzacchi** [comment]
Necesitaríamos 10000 caracteres

**Comment by tvalzacchi** [comment]
Fede, ¿porque me asignaste esto a mi? Necesitamos los caracteres ahora como esta no se pueden cargar relevamientos. Antes de modificar algo en el g-obra llamanos porque estamos con gente de UEP por cargar

**Comment by fhatzen** [comment]
Quedó subida la posibilidad de cargar textos con formato utilizando copiar y pegar (sin fotos), como ejemplo pegué este documento de 19 páginas en la obra con exp. 0753965, ESCUELA SECUNDARIA Nº32 MARY O GRAHAM
