### ISSUE TITLE
Boton eliminar en licitaciones

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#54]
Fede el boton eliminar aparece fugazmente cuando ingresas, y luego se va 

![image](https://cloud.githubusercontent.com/assets/17601411/13671789/c61e2ab8-e6b0-11e5-83a8-be7255b93eb7.png)

![image](https://cloud.githubusercontent.com/assets/17601411/13671799/d1559cae-e6b0-11e5-9bd6-4ddf47ef2649.png)

**Comment by fhatzen** [comment]
por favor confirmar que el usuario utilizado tiene permisos de alta,
modificación y BAJA sobre el menú principal, si este era el problema por
favor cerrar el caso, gracias!

**Comment by tvalzacchi** [comment]
Estaba con mi usuario q tengo permisos para eliminar

**Comment by fhatzen** [comment]
resuelto el caso, SIGUIENTE!!!!
