### ISSUE TITLE
Fotos en Relevamiento

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#55]
Se debería agregar un botón de carga de fotos en el relevamiento, y que las fotos que son de este relevamiento las pueda ver (ahora no puedo ver fotos en esta solapa)

![image](https://cloud.githubusercontent.com/assets/17601411/13672202/876de748-e6b2-11e5-9b20-97cd3d15769a.png)

**Comment by fhatzen** [comment]
se hizo tal como idicado
