### ISSUE TITLE
servicios relevamiento

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#56]
Levanto pedido de crisa hecho por wsapp,  esto tendria que ser un si/no en el relevamiento
![img_6708](https://cloud.githubusercontent.com/assets/17601411/13672642/7a2414a2-e6b4-11e5-9d97-def184302514.JPG)

**Comment by fhatzen** [comment]
es un dato del establecimiento o de la licitación?

**Comment by tvalzacchi** [comment]
Buena pregunta, ahora como esta funcionando forma parte de la licitacion, pero a futuro podriamos tener los relevamientos vinculados a establecimientos

**Comment by fhatzen** [comment]
@elcrisa tomi te reasigno esto hasta que decidan donde van estos datos, de aquí en más tenemos que pensar bien qué va a establecimiento, qué va a expediente y qué va a licitación, para hacer un ajuste más o menos definitivo al diseño de las tablas...

**Comment by tvalzacchi** [comment]
@fhatzen va a relevamiento en la licitación

**Comment by fhatzen** [comment]
agregados los campos en solapa "relevamiento"

**Comment by tvalzacchi** [comment]
Fede, lo ideal sería que sea como los del sistemode verificación de documentación de **si/no/no sabe** , ya que al estar como esta se puede intepretar que no hay un servicio que en realidad no fue relevado

**Comment by tvalzacchi** [comment]
que sea campo obligatorio
