### ISSUE TITLE
Nueva solapa "llamado"

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#57]
Fede deberíamos ya incorporar una nueva solapa previa a **Oferentes** , la misma por ahora podría llamarse **Llamado** , el contenido debería ser como esta ahora para elegir por cuit los contratistas (en este caso no se elegirían más en Oferentes), y también debería figurar el presupuesto oficial de los distintos lotes

NO todos los invitados serán oferentes, algunos tal vez no envíen su propuesta. El máximo es 6.

También deberíamos tener para adjuntar abajo las **Circulares ** que emite la UEP. Estas pueden ser con consulta y sin consulta. Por ahora nos asigno esto a crisa y a mi hasta que la pulamos más y te la asignemos a vos.

**Comment by fhatzen** [comment]
estos son datos del expediente o de la licitación? tenemos que empezar a
discriminarlos para que haga la separación lo antes posible; en principio
supongo que si los oferentes son por todos los lotes del expediente, los
invitados también lo serán

2016-03-10 12:11 GMT-03:00 tvalzacchi <notifications@github.com>:

**Comment by tvalzacchi** [comment]
Los invitados son por todos los lotes, a futuro podríamos generar la invitación desde el gobra. La cascada ahora comenzaría con los que cargue en llamado, es decir en oferentes elijo los del llamado, y en contratista elijo uno de los oferentes. Vamos para adelante con esta solapa

**Comment by tvalzacchi** [comment]
En esta solapa de llamado, se debería colocar botones para adjuntar las **Publicaciones en Boletín Oficial** , **Publicaciones en Periodicos**

**Comment by fhatzen** [comment]
Completada la separación de "llamado" y "oferentes", trasladando a "llamado" el alta y baja de invitados y dejando en "oferentes" sólo la carga de ofertas, comentarios y demás.
