### ISSUE TITLE
error creando nueva obra

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#58]
Seleccione establecimientoy exploto
![image](https://cloud.githubusercontent.com/assets/17601411/13677409/a5da101a-e6c8-11e5-97f3-604099e43318.png)

**Comment by tvalzacchi** [comment]
Perdon mande fruta

**Comment by tvalzacchi** [comment]
Fede la obra la borramos y la queremos cargar de vuelta y surge este error
![image](https://cloud.githubusercontent.com/assets/17601411/13677532/16e29142-e6c9-11e5-8046-e5fc8ed68483.png)

**Comment by fhatzen** [comment]
resuelto, no se considerarán licitaciones eliminadas
