### ISSUE TITLE
Supervisores vinculados a regiones

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#60]
Cada region tiene siempre un unico "Coordinador Regional" asignado. Agregar campo para vincular cada supervisor a cada region. Utilizar la columna grupo cambiando su nombre a  "Coordinador Regional" 
![image](https://cloud.githubusercontent.com/assets/17600443/13678593/4277219c-e6ce-11e5-9f06-49118a344725.png)

**Comment by fhatzen** [comment]
hecho

**Comment by tvalzacchi** [comment]
Fede dice ''Responsable'', se puede poner ''Coordinador general'' como le dicen ahora?

**Comment by elcrisa** [comment]
Tomar el dato segun region y colocarlo junto al texto "Supervisor" (en realidad debe decir "coordinador regional".
![image](https://cloud.githubusercontent.com/assets/17600443/13707626/4f1b55b0-e789-11e5-9433-ce0bf7db4a2c.png)

**Comment by fhatzen** [comment]
al crear nuevas obras, se tomará el coordinador regional de la región del CUE; en las obras antiguas no tomaremos el dato directamente porque la región puede cambiar su coordinador regional pero el que estaba en ese momento en la obra, debe permanecer junto a la historia de la obra

**Comment by elcrisa** [comment]
El coordinador regional debera ser tomado siempre (en nuevas y antiguas) de la region correspondiente.

**Comment by tvalzacchi** [comment]
No debe ser posible elegir el coordinador general, sino que se asignaría automáticamente

**Comment by fhatzen** [comment]
el coordinador regional ya no se puede elegir, depende de la región de la escuela
