### ISSUE TITLE
Cotejar que la suma de items sume el mismo valor que el valor del "monto oferta" para el mismo oferente seleccionado, mensaje de alerta si esto no sucede.

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#62]
![image](https://cloud.githubusercontent.com/assets/17600443/13703197/f2be420c-e772-11e5-964b-1a6f2c5e220c.png)
![image](https://cloud.githubusercontent.com/assets/17600443/13703232/3826dbba-e773-11e5-9eba-4b5add1f9da0.png)

**Comment by fhatzen** [comment]
Agregados los mensajes de alerta por inconsistencias
