### ISSUE TITLE
Generador de usuarios nuevos su clave, validacion y recuperacion de contraseña

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#63]
Procedimiento para el alta de usuario:

1. - Se le solicita en persona al nuevo usuario su nombre y direccion de mail.
2. - Se carga como hasta ahora el nombre y apellido, el mail y el USR (inicial de nombre y apellido corridos y en minuscula)
3. - G-obra genera una clave alfanumerica de 8 caracteres con al menos una letra en mayuscula envia un mail automatico al usuario con estos datos.
4. - En el mail se le dice que debe cambiar su contraseña y que clikee un link a G-obra a una pantalla de login difrenciada (desde ahora Login B) de la comun (desde ahora Login A)
5. - En este login B, se le da la bienvenida, se le solicita que cargue su usuario, la contraseña enviada por mail, su nueva contraseña (alfanumerica de 8 caracteres con al menos una letra en mayuscula) y nuevamente esta contraseña para su validacion.
6. - De ahi en mas siempre accedera a la pantalla Login A, la cual es la misma que la actual pero abajo de la clave aparece un link con la leyenda "Reestablecer Contraseña"
7. - En este caso, al hacer clik en el link,  una pantalla le solicita que ingrese su usuario y su mail, una vez validado se le avisa que se le enviara un mail, se continua coon el paso 3
![image](https://cloud.githubusercontent.com/assets/17600443/13704358/3b5a61f6-e77a-11e5-87c7-a0b5fae1e80c.png)
Habria que eliminar de la pantalla de configuracion de usuario los campos "clave" y "repetir clave"

**Comment by tvalzacchi** [comment]
@fhatzen  Entiendo que esto no va a estar en lo inmediato, y que lo iba a hacer Luciano, pero que posibilidad hay de un plan B? se me ocurre que podríamos generar aunque sea un boton que los lleve a enviar un mensaje de olvido de clave en el que pongan el mail, así de esa forma podemos tener esa opción para que la gente no se frene

**Comment by tvalzacchi** [comment]
![pagina 001-modif](https://cloud.githubusercontent.com/assets/17601411/13882449/34090ada-ed04-11e5-93f3-94107571434e.jpg)

**Comment by elcrisa** [comment]
![image](https://cloud.githubusercontent.com/assets/17600443/13887748/3d7c68c4-ed1c-11e5-945a-5daab87546aa.png)
No puedo modificar el campo nombre!!!!!!

**Comment by elcrisa** [comment]
No se pueden eliminar usuarios, al tocar la "X" entra a modo edicion.

**Comment by elcrisa** [comment]
El sistema para restablecer la contraseña aun no funciona como lo solicitado, le genera al usuario una clave jeroglifica que es imposible de recordar y de cambiar por otra que el desee.

**Comment by fhatzen** [comment]
quedó resuelto el tema claves, en pantalla de inicio el usuario puede colocar una clave fácil si lo desea
