### ISSUE TITLE
Cuit no encontrado

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#68]
Fede, un cuit no lo encuentra

![image](https://cloud.githubusercontent.com/assets/17601411/13729330/1f7a1722-e911-11e5-9f90-65c1962c84ef.png)

**Comment by fhatzen** [comment]
![image](https://cloud.githubusercontent.com/assets/5720861/13730488/89b2deda-e92f-11e5-803c-77820fabd7a8.png)

fijate que tampoco está en la base AFIP, da un error

igual tenemos que ver qué hacemos con esto, si aceptamos o no CUIT irregulares

**Comment by tvalzacchi** [comment]
Fede, tira ahora q tiene constancia, pero en el g-obra no

![image](https://cloud.githubusercontent.com/assets/17601411/13931705/545b87c8-ef83-11e5-946d-a8d01d8354f7.png)

**Comment by fhatzen** [comment]
Modifiqué el funcionamiento de esto. Al cargar un CUIT viene automáticamente la razón social. Si esta no existiera  (o si deseara modificar su nombre), el usuario podrá cargar una en el momento, completando el cuadro. En columna aparte quedará la razon social "AFIP" si existiera en el padrón
