### ISSUE TITLE
región distrito CUE 

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#69]
Obra con CUE asignado, no trae a listado de Licitaciones los datos de región y distrito.

![image](https://cloud.githubusercontent.com/assets/17601411/13729350/9c5ed6b0-e911-11e5-979b-e280a12e7e9b.png)

**Comment by fhatzen** [comment]
resuelto!

**Comment by tvalzacchi** [comment]
Fede, reabro este tema ya que tal vez esta relacionado, cuando le cambio el CUE a alguna licitación no me trae los datos de region/distrito/establecimiento

![image](https://cloud.githubusercontent.com/assets/17601411/13782431/cbf2cdb0-eaa5-11e5-8404-4c93c100b202.png)

**Comment by elcrisa** [comment]
![image](https://cloud.githubusercontent.com/assets/17600443/13860524/894044d4-ec67-11e5-8bc4-411bec1d9ae7.png)

**Comment by fhatzen** [comment]
corregido que cuando se cambia el CUE no se traían los datos del establecimiento y también corregido el histórico de registros que habían quedado sin establecimiento
