### ISSUE TITLE
Acta común a todos los lotes

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#71]
Fecha de apertura, días de validez de oferta, y el acta adjunta son comunes a todos los lotes, ahora como esta lo tengo que cargar en todos por separado. Tampoco ahora me deja descargar el acta adjunta, lo cual estaría bueno en esa pantalla y no en la final

![image](https://cloud.githubusercontent.com/assets/17601411/13749047/7d8f6330-e9de-11e5-9700-c5a9c1fbad5b.png)

**Comment by fhatzen** [comment]
Se unificó en el nivel de "expediente" la fecha de apertura de ofertas, plazo de vigencia y adjuntos de la solapa "oferente"; se agregó en la solapa "oferente" la lista de adjuntos del estado correspondiente

**Comment by elcrisa** [comment]
Para la pestaña "Contratista", pasa lo mismo que para las "actas". Como la adjudicacion de los N lotes de una cotizacion se realiza siempre al mismo oferente, al ser adjudicado este pasa a ser "contratista" en cualquier lote y deberia aparecer en los lotes restantes la misma seleccion .

![image](https://cloud.githubusercontent.com/assets/17600443/13780174/0e73ba22-ea9d-11e5-8b6a-1f553d53735c.png)
Al ser seleccionado el importe (suma total de lotes adjudicados) deberia aparecer en el campo "Monto contratado original"
![Uploading image.png…]()

**Comment by fhatzen** [comment]
Realizado este requerimiento excepto: "Al ser seleccionado el importe (suma total de lotes adjudicados) deberia aparecer en el campo "Monto contratado original"". El importe está discriminado por licitación, mando a cada licitación el importe correspondiente al contratista seleccionado y en la suma de lotes del expediente dará el total contratado para el expediente
