### ISSUE TITLE
Ver montos en listado de licitación

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#72]
este es un pedido de gente de la UEP

Al poner ver montos lo que muestra como **Presupuestado** debería llamarse **Presupuesto Oficial**. También debería ver el **Suma ítems oficial**  y el **Dif. suma ítems y P.O.**

También agreguemos **Dif. entre P.O. y Contratado**

La idea es ya poder filtrar un listado con estas diferencias para ver con los directivos

![image](https://cloud.githubusercontent.com/assets/17601411/13750685/520f8756-e9e5-11e5-8fda-cf9bd6dc1825.png)

**Comment by fhatzen** [comment]
agregadas estas columnas y filtros, como se muestra en la imagen

![image](https://cloud.githubusercontent.com/assets/5720861/13768795/97e5fa44-ea58-11e5-8065-dde7d0b032fb.png)
