### ISSUE TITLE
separador de miles y decimales para todos los valores

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#73]
Al cargar se cargan los decimales luego de un punto.
Al mostrase se veria asi:
- $ 1,000.32  (coma miles y punto en decimales)

Agregar el Signo $

**Comment by elcrisa** [comment]
se deberia permitir la carga decimal **indistintamente** con punto o con coma, pero la visualizacion deberia ser siempre asi:   1.234,65
Se separan miles con puntos y decimales con coma.

**Comment by fhatzen** [comment]
se realizó este requerimiento
