### ISSUE TITLE
Boton para cargar solo un documento especifico

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#74]
Boton "Adjuntar Acta de apertura de Ofertas y otros documentos del estado Evaluación de las Propuestas" pasa a :"Adjuntar Acta de apertura de Ofertas".
El texto del boton indica el documento requerido a subir y puede ser solo un documento y se sube unicamente en la pestaña en que esta dicho boton.
Se podra subir solo un archivo (notar que en la imagen se ve que se subieron 3). Si se desea reemplazar el archivo subido se debera eliminar primero y luego subirlo.
No permitir carga multiiple en este caso ya que hay solo una unica Acta de apertura de Ofertas.
![image](https://cloud.githubusercontent.com/assets/17600443/13779511/078bf0a6-ea9a-11e5-9a4c-3e55c2738856.png)

**Comment by fhatzen** [comment]
Ojo Crisa que se ven tres documentos porque se subio uno por cada
licitación, al unificarse partes de la licitación al nivel de "expediente"
aparecen estos tres documentos, que en realidad probablemente son el mismo.

2016-03-15 10:38 GMT-03:00 elcrisa <notifications@github.com>:

**Comment by elcrisa** [comment]
OK, sospeche eso. Ahora elimino los sobrantes. Tenes que impedir que se suba mas de uno por Exepdiente, se carga solo una sola vez indistintamente en cualquier lote, por lo que deberia desaparecer este boton si el archivo ya fue adjuntado y reapareceria solo si en cualquier lote se elimina el adjunto.

**Comment by fhatzen** [comment]
ajustado el botón, paso el requerimiento de "limitar a uno solo por expediente" a otro issue, ya que está relacionado intimanente con workflow
