### ISSUE TITLE
Poder ordenar lista de licitaciones por "dif. %"

### ISSUE THREAD

**Issue by fhatzen** [fhatzen/geobra#77]

**Comment by tvalzacchi** [comment]
fede probamos de usar el botón incorporado pero no estaría funcionando

![image](https://cloud.githubusercontent.com/assets/17601411/13847251/05219e28-ec2b-11e5-8dd8-a10e4ac9dfe5.png)

**Comment by fhatzen** [comment]
corregido el ordenador
