### ISSUE TITLE
Error con unidad de medida

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#79]
Cuando cargo un C y P oficial, elegida la unidad de medida al poner guardar, cambia todas a Global

![image](https://cloud.githubusercontent.com/assets/17601411/13817527/5a5f9080-eb71-11e5-8e99-40199a145419.png)

![image](https://cloud.githubusercontent.com/assets/17601411/13817549/6ab519fa-eb71-11e5-9c9e-37d0d66b1e27.png)

**Comment by fhatzen** [comment]
Resuelto este error
