### ISSUE TITLE
Modificaciónes pantalla contratista

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#81]
![uep pantalla contratista](https://cloud.githubusercontent.com/assets/17601411/13827137/b9725724-eb99-11e5-90ad-4e82848afa95.jpg)

**Comment by elcrisa** [comment]
No deberia aparecer la opcion de 5 (cinco) adjuntos, es solo uno por cada boton especifico. Ademas no deberia aparecer el desplegable para seleccionar contratista ya que este se define solo junto al boton amarillo "cargar contratista"

**Comment by fhatzen** [comment]
Resuelto requerimiento según indicaciones.
