### ISSUE TITLE
Pestaña y Pantalla para cargar contenido Invitacion

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#84]
Pestaña a ubicar segun imagen y con la siguiente plantilla de upload/download.
![grafico1](https://cloud.githubusercontent.com/assets/17600443/13848679/b063611c-ec31-11e5-9973-136132602fda.jpg)

**Comment by elcrisa** [comment]
Se unifican en la solapa "Llamado" #57 este requerimiento y el solicitado en #57
No se incorporaria la solapa "Contenido Invitacion".
![image](https://cloud.githubusercontent.com/assets/17600443/13858307/c8d86abe-ec5c-11e5-96e8-a5986dbe7aed.png)
Antecediendo a los botones Azules "Adjuntar public....." se colocara el listado de carga especificado en 
![image](https://cloud.githubusercontent.com/assets/17600443/13858381/2ea19d3e-ec5d-11e5-9daa-5a060b33ec50.png)

**Comment by fhatzen** [comment]
Se replicó en g-obra el funcionamiento indicado aquí

**Comment by fhatzen** [comment]
SE cambió el sistema de adjuntar, pasándose a un modelo en el cual las solapas "llamado", "propuestas", "contratista" y "recepciones" contienen la grilla de documentos esperados (volcados por Tomas en configuración - documentos y luego incoporados a los programas FREC, etc. dentro de configuración - programas), los cuales son completados por el usuario. Disponible en la actualización que haré hoy a ultima hora @tvalzacchi  @elcrisa
