### ISSUE TITLE
Botón único para modicar

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#85]
El botón para modificar, podría ser uno solo que sea Modificar, ya que ahora dice cargar adendas

![image](https://cloud.githubusercontent.com/assets/17601411/13849201/e9df7bcc-ec33-11e5-837f-916550783059.png)

**Comment by fhatzen** [comment]
Modificado el botón y simplificado el funcionamiento de los múltiples botones amarillos, sólo piden permiso una vez y luego desaparecen, quedando todo habilitado para la carga hasta que incorporemos workflow / permisos por rol
