### ISSUE TITLE
Solapa Certificados y Solapa Recepciones

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#86]
![g-obra- pestanas nuevas-01](https://cloud.githubusercontent.com/assets/17600443/13858868/523ebedc-ec5f-11e5-8de7-1c0c8945ae3b.jpg)
Se agrega la Solapa Certificados y Solapa Recepciones, se reubica la solapa LOG

**Comment by fhatzen** [comment]
Agregadas ambas solapas, la de certificados con su correspondiente funcionalidad
