### ISSUE TITLE
Titulo en diferencia entre Presup. Oficial y Contratado

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#89]
Fede, habría que poner un título a la diferencia porcentual entre el presup. oficial y el contratado (ellos lo llaman variación) y que en los casos en los que esta contratado, que tire un alerta si supera el 20% del mismo. 

Podría decir  **''El monto contratado supera en más del 20% el presupuesto oficial, deberá solicitarse la no objeción de la Dirección General de Infraestructura del Ministerio de Educación de la Nación''**

![image](https://cloud.githubusercontent.com/assets/17601411/13881210/aad81f94-ecfe-11e5-9770-85ad5d0f32f9.png)

**Comment by fhatzen** [comment]
agregado este diferenciador con marca naranja en lista principal de licitaciones y agregado a la lista de alertas (al ingresar a la licitación)
