### ISSUE TITLE
Impedir modificacion de datos Caratula en estados avanzados

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#91]
No permitir que se modifiquen campos (Ej: Establecimiento) cuando se ha avanzado como en el caso de licit 222 hasta la certificacion. Deberia impedirse esta modificacion a partir de la carga de cualquier valor en la solapa "relevamiento"

**Comment by fhatzen** [comment]
Se agregó una validación que impide modificar carátula si se ha cargado fecha de relevamiento. Observar que estamos metiendo un workflow por la ventana
