### ISSUE TITLE
Flechas rojas de orden no funcionan al menos en esta pantalla

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#92]
Revisar en otras pantallas si sucede lo mismo.
![image](https://cloud.githubusercontent.com/assets/17600443/13923661/56744ed2-ef60-11e5-89e2-14e4ab7bf2ec.png)

**Comment by elcrisa** [comment]
solo funciona la que indica hacia abajo

**Comment by fhatzen** [comment]
Ajustado el funcionamiento de las flechas
