### ISSUE TITLE
Tema copete

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#94]
Fede Crisa te va a llamar, creo el github para que quede asentado, en la 222 de prueba el C y P contratado y el Plan de Trabajo no tienen los mismos montos, al parecer le estaría sumando el copete, pero en elC y P cocntratado ya tiene el Copete. Por lo que entendemos la única razón de ser del copete sería para hacer un analisis de precios del ítem

**Comment by fhatzen** [comment]
Se corrigió el tema de copetes, los cálculos se realizan, a modo informativo (e inversamente, o sea restando) en las solapas cómputo y presupuesto oficial y c.y p. contratado, en un cuadro debajo de los ítems
