### ISSUE TITLE
CERTIFICADOS PDF (TODOS LOS PDF´s GENERADOS)....deben der INTANGIBLES

### ISSUE THREAD

**Issue by elcrisa** [fhatzen/geobra#95]
![image](https://cloud.githubusercontent.com/assets/17600443/13956384/4df4512c-f027-11e5-9e2c-29095dfa03cb.png)
  modifique los valores del certificado 4, y sorpresa el PDF generado no es un documento INTANGIBLE sino una imagen cambiente!!!!

![image](https://cloud.githubusercontent.com/assets/17600443/13956432/79b53ed4-f027-11e5-9ffe-ccc42d25e778.png)

**Comment by fhatzen** [comment]
Agregada una traba que impide generar nuevos PDF de certificados hasta no eliminar los PDF de certificados anteriores
