### ISSUE TITLE
Variacion

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#96]
Fede cuando hace la cuenta de la variación entre el Presup. Oficial y el Contratado, no debería hacer la cuenta si no hay un monto de contrato cargado, o un contratista cargado

![image](https://cloud.githubusercontent.com/assets/17601411/13957295/b73b46b0-f02a-11e5-8b0e-64b3192e503f.png)

**Comment by tvalzacchi** [comment]
Fede, veo que eso esta solucionado, agrego el tema de que está sumando los porcentajes de variables y no debería, lo hace confuso

![image](https://cloud.githubusercontent.com/assets/17601411/13984066/9e84e15a-f0d2-11e5-897e-d70b330555b0.png)

**Comment by fhatzen** [comment]
eliminada la suma de porcentajes
