### ISSUE TITLE
Copiar  y pegar relevamiento

### ISSUE THREAD

**Issue by tvalzacchi** [fhatzen/geobra#97]
Fede,sucede que cuando copiamos y pegamos en el cuadro de texto, si no pones **Pegar como texto sin formato** se cuelga. ¿Puede hacerse que pegue por defecto sin formato?

**Comment by fhatzen** [comment]
Estimados, por favor comprobar esto nuevamente. Mejoré la administración del contenido del cuadro (bastante indomable de por sí, sobre todo si se vuelva mucho texto), la idea es que puedan copiar y pegar texto CON formato. Como consecuencia de estas mejoras, este cuadro relevamiento es uno de los pocos campos de datos que requieren que se presione el botón "guardar" (aunque en este momento tanto el botón CERRAR realiza automáticamente el guardado)

@elcrisa  Además seteé que luego de guardar, la pantalla se recargue en la solapa donde se estaba operando anteriormente. Por favor pidanme las cosas para que las pueda hacer.
